# 
spring.datasource.url=jdbc:mysql://localhost:3306/applicant_db?useSSL=false&serverTimezone=Asia/Tokyo

spring.datasource.username=root
spring.datasource.password=YuuDisney12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# --- 送信メールアカウントの種類を切り替え ---
mail.provider=gmail   #gmail/icloud を選択

#iCloudメール送信
#spring.mail.host=smtp.mail.me.com
#spring.mail.port=587
#spring.mail.username=you0217maikww@icloud.com
#spring.mail.password=dixs-fibf-addq-gsha
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.default-encoding=UTF-8

# Gmail 用設定
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# JavaMail debugログを有効化
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG

# MySQLに接続
#spring.datasource.url=jdbc:mysql://localhost:3306/applicant_db?useSSL=false&serverTimezone=Asia/Tokyo
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



